name: Conventional Changelog Action
uses: TriPSs/conventional-changelog-action@v1.3.0
on: [push]
branches: [master]
with:
  github-token: ${{ secrets.github_token }}
  git-message: 'chore(release): {version}'
  preset: 'angular'
  tag-prefix: 'v'
  output-file: 'CHANGELOG.md'
  changelog-release-count: 5
